# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GzxkH-Jf0lCVBNtfTfYi8d2GYpwI2IG
"""

# import
import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

accessToken='1393886621729271815-MSUMYiX5E7dOqv688WtlRDL861LVEg'
accessTokenSecret='kRPXGNrEecnKUTg1n0Xm4nxFQ22loyuoKkFdbjzSYdskM'
consumerKey='JR6B8K1QWpYeMqMKYAiGkIF3l'
consumerSecret='A83zp1kFCtrBTNmpwNnxXWRLRTsSshmRkRkl9MV29Bu7DYkBZm'

auth = tweepy.OAuthHandler(consumerKey,consumerSecret)
auth.set_access_token(accessToken,accessTokenSecret)
api=tweepy.API(auth,wait_on_rate_limit=True)

# get n tweets from Elon Musk, n=10 
posts = api.user_timeline(screen_name='ElonMusk',count=10,lang="en",tweet_mode="extended")

df = pd.DataFrame([tweet.full_text for tweet in posts],columns=['Tweets'])
#df.head()


############
# performance test handle
@profile
def print_tweets(num):
  #print("show the n recent tweets:\n")
  i = 0
  for tweet in posts[0:num]:
    i+=1
    #print(str(i)+')'+tweet.full_text+'\n')
  return i

def cleanTxt(text): #str
  text = re.sub(r'@[A-Za-z0-9]+','',text)
  text = re.sub(r'#','',text)
  text = re.sub(r'RT[\s]+','',text)
  text = re.sub(r'https:\/\/S+','',text)
  return text

def getSubjectivity(text):
  try: 
    return TextBlob(text).sentiment.subjectivity
  except:
    return ("please input text")
def getPolarity(text):
  try:
    return TextBlob(text).sentiment.polarity
  except:
    return ("please input text")

def getAnalysis(score):
  if score < 0:
    return 'Negative'
  elif score==0:
    return 'Middle'
  else:
    return 'Positive'

if __name__ == "__main__":
  print_tweets(10)
  cleanTxt('1234')
  cleanTxt('@1234')
  cleanTxt('#1234')
  cleanTxt('https://www.baidu.com')
  getSubjectivity('ABCD')
  getSubjectivity('I LOVE ECE')
  getPolarity('I AM UPSET')
  getPolarity('I AM HAPPY')
  getAnalysis(12)
  getAnalysis(85)
  getAnalysis(60)
